apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      serverName: account-service
  template:
    metadata:
      labels:
        serverName: account-service
    spec:
      nodeSelector:
        node: api
      containers:
        - name: account-service-v1
          image: meghanakouchika/account-service:v22
          ports:
            - containerPort: 8081
          env:
            - name: name
              #value: Current
              valueFrom:
                configMapKeyRef:
                  name: properties-configmap
                  key: accountName
